[workspace]
authors = ["hyzhou"]
channels = ["conda-forge"]
name = "HUGSIM"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-apex = { cmd = "sh -c '[ -d apex ] || git clone https://github.com/NVIDIA/apex.git apex' && cd apex && git checkout ac8214ee6ba77c0037c693828e39d83654d25720 && python setup.py install --cuda_ext --cpp_ext", cwd = "data/InverseForm"}

[dependencies]
python = "==3.11.10"
setuptools = "==78.1.0"

[pypi-options]
no-build-isolation = ["gsplat", "pytorch3d", "tinycudann", "simple-knn"]

[pypi-dependencies]
torch = { version = "==2.4.1", index = "https://download.pytorch.org/whl/cu118" }
torchvision = { version = "==0.19.1", index = "https://download.pytorch.org/whl/cu118"}
torchmetrics = ">=1.7.1, <2"
roma = ">=1.5.2.1, <2"
matplotlib = ">=3.10.1, <4"
tqdm = ">=4.67.1, <5"
opencv-python = ">=4.11.0.86, <5"
scipy = ">=1.15.2, <2"
einops = ">=0.8.1, <0.9"
trimesh = ">=4.6.6, <5"
tensorboard = ">=2.19.0, <3"
gpustat = ">=1.1.1, <2"
scikit-learn = ">=1.6.1, <2"
open3d = ">=0.18.0, <0.19"
timm = ">=1.0.15, <2"
geometry = ">=0.0.23, <0.0.24"
gymnasium = "==1.1.1"
imageio = ">=2.37.0, <3"
jaxtyping = ">=0.3.1, <0.4"
mediapy = ">=1.2.3, <2"
omegaconf = ">=2.3.0, <3"
pillow = ">=11.2.1, <12"
plyfile = ">=1.1, <2"
pyquaternion = ">=0.9.9, <0.10"
pyyaml = ">=6.0.2, <7"
shapely = ">=2.1.0, <3"
tabulate = ">=0.9.0, <0.10"
protobuf = "==3.20.2"
runx = "==0.0.6"
fire = ">=0.7.0, <0.8"
ninja = ">=1.11.1.4, <2"
h5py = ">=3.13.0, <4"
nose = ">=1.3.7, <2"
dominate = ">=2.9.1, <3"
cffi = ">=1.17.1, <2"
piexif = ">=1.1.3, <2"
jupyter = ">=1.1.1, <2"
ipdb = ">=0.13.13, <0.14"
numpy = ">=1.24.3, <2"
torch-fidelity = ">=0.3.0, <0.4"
huggingface-hub = ">=0.32.0, <0.33"

# install from source code
hugsim-env = { path = "./sim", editable = true }
simple-knn = { path = "./submodules/simple-knn", editable = false }
gsplat = { git = "https://github.com/hyzhou404/HUGSIM_splat.git", rev = "main" }
flow-vis-torch = { git = "https://github.com/ChristophReich1996/Optical-Flow-Visualization-PyTorch", rev = "main" }
unidepth = { git = "https://github.com/hyzhou404/UniDepth.git", rev = "main" }
trajdata = { git = "https://github.com/hyzhou404/trajdata.git", rev = "main" }
tinycudann = { git = "https://github.com/NVlabs/tiny-cuda-nn", rev = "master", subdirectory="bindings/torch" }
kitti360Scripts = { git = "https://github.com/autonomousvision/kitti360Scripts.git", rev = "master" }
simple-waymo-open-dataset-reader = { git = "https://github.com/gdlg/simple-waymo-open-dataset-reader.git", rev = "master" }
pytorch3d = { git = "https://github.com/facebookresearch/pytorch3d.git", rev = "stable" }
nuscenes-devkit = { git = "https://github.com/hyzhou404/nuscenes-devkit.git", rev = "master"}
moviepy = ">=2.2.1, <3"

